//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokedex.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokemons
    {
        public int Id { get; set; }
        public Nullable<int> AmountOnWorld { get; set; }
        public string Name { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> ImageId { get; set; }
    
        public virtual PokemonPictures PokemonPictures { get; set; }
        public virtual PokemonTypes PokemonTypes { get; set; }
    }
}
